[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21"
diesel = { version = "2.1.1", features = ["postgres"] }
dotenv = "0.15.0"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
rocket_db_pools = { version = "=0.1.0-rc.3", features = ["sqlx_postgres"] }
serde = "1.0.188"
sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio-rustls"] }
rustix = "0.38.19"