on: [push]

name: CI

jobs:
  build_and_test:
    name: wol-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move into project
        run: cd backend
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.1
        with:
          # For now just build
          # Will probably keep this to ensure that the app actually compiles
          # Make sure no stupid mistakes get into the code base
          command: build
          args: --release --all-features
          # Add test step later
